import { GoogleGenAI } from '@google/genai';
import { GitLabAPI } from '../gitlab';

const getAI = () => new GoogleGenAI({ apiKey: process.env.GEMINI_API_KEY });

export class BuilderAgent {
  static async execute(plan: any, issueId: string | number, gitlab: GitLabAPI) {
    const branchName = `feature/issue-${issueId}-auto`;
    await gitlab.createBranch(branchName);

    const prompt = `You are the Builder Agent. Generate the code for the following plan:
    ${JSON.stringify(plan)}
    
    Output ONLY a JSON array of file objects with 'file_path' and 'content'. No markdown formatting outside the JSON.`;

    const response = await getAI().models.generateContent({
      model: 'gemini-3.1-pro-preview',
      contents: prompt,
      config: {
        responseMimeType: 'application/json'
      }
    });

    let files = [];
    try {
      files = JSON.parse(response.text || '[]');
    } catch (e) {
      console.error("Failed to parse Builder Agent response", e);
    }

    const actions = files.map((f: any) => ({
      action: 'create',
      file_path: f.file_path,
      content: f.content
    }));

    if (actions.length > 0) {
      await gitlab.commitFiles(branchName, `Auto-generated code for issue #${issueId}`, actions);
    }

    const mr = await gitlab.createMergeRequest(
      branchName, 
      'main', 
      `Resolve Issue #${issueId}: Auto-generated implementation`, 
      `This MR was automatically generated by the ADC Builder Agent based on Issue #${issueId}.`
    );

    return { branchName, mrId: mr.iid, filesGenerated: files.length };
  }
}
